import initTabNav from "./modules/tabnav.js";
import initAccordion from "./modules/accordion.js";
import initScroll from "./modules/scroll-anima.js";
import initScrollAnima from "./modules/scroll.js";
import initModal from "./modules/modal.js";
import initTooltip from "./modules/tooltip.js";
import initDropdownMenu from "./modules/dropdown-menu.js";
import initMenuMobile from "./modules/menu-mobile.js";
import initAnimaNumeros from "./modules/anima-numeros.js";
import initFetchAnimais from "./modules/fetch-animais.js";
import initFuncionamento from "./modules/funcionamento.js";

initTabNav();
initAccordion();
initScroll();
initScrollAnima();
initModal();
initTooltip();
initDropdownMenu();
initMenuMobile();
initAnimaNumeros();
initFetchAnimais();
initFuncionamento();